version: '3.8'

services:
  app:
    ports:
      - '3000:3000'
    volumes:
      - .:/app

  postgres:
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local